version: '3.8'

services:
  reubah:
    image: ghcr.io/ma-04/reubah:latest
    ports:
      - "8081:8081"
    volumes:
      - ./tmp:/app/tmp
      - doc-temp:/tmp
    environment:
      - PORT=8081
    restart: unless-stopped 

volumes:
  doc-temp: 